### ISSUE TITLE
Saving extra tag files in directory (not in bag itself!)

### ISSUE THREAD

**Issue by Bolkun** [jscancella/bagging#43]
## When submitting an issue please include:
* a small code example showing the incorrect behavior
BagBuilder builder = new BagBuilder();
		builder.addAlgorithm("md5")
                        .addMetadata("foo", "bar")		
			.addPayloadFile(payloadFiles)
			**.addTagFile(Paths.get(absolute_dir + "/import/meta"))**
			.bagLocation(Paths.get(absolute_dir + "/export/bag)
			.write();

* the expected behavior
_Structure of Bag MUST be_
data
**meta** (with files for example: **mods.xml**, **rights.xml**)
bag-info.txt
bagit.txt
manifest-md5.txt
tagmanifest-md5.txt (Must include: xxxxxxxxxxxxxxxxxxxxxxxx **meta/mods.xml**)
                                  (Must include: xxxxxxxxxxxxxxxxxxxxxxxx **meta/rights.xml**)

* the actual behavior
_Structure of Bag INCORRECT_
data
**mods.xml**
**rights.xml**
bag-info.txt
bagit.txt
manifest-md5.txt
tagmanifest-md5.txt

* the operating system being used, and its version
debian 10
* version of Bagging being used
4.2

**Comment by jscancella** [comment]
Need to add a check on line https://github.com/jscancella/bagging/blob/master/src/main/java/com/github/jscancella/domain/BagBuilder.java#L179 
If it is a directory, then it should be `builder.addFile(tagFile, rootDir.relativize(tagFile));` or something like that. Be sure to add a test case for this!

**Comment by jscancella** [comment]
This should be fixed in version 4.3
