### ISSUE TITLE
Question from a newbie (all around!)

### ISSUE THREAD

**Issue by ahva-ubc** [jscancella/bagging#54]
Hi there,

I am sort of tech savvy (enough for creating disasters!) but not a developer by any means. I cloned your repo and tried the library (I think!) It might be good for beginners like me to include more information on how to actually use this. Is the basic way to use this as follows?

1. Open the command line and navigate to where the code lives, e.g., C:\Users\User\Documents\GitHub\bagging
2. Write a command like: 
Path outputDir = Paths.get("C:\Users\User\Desktop\b_latour_iconoclash_images_bag"); bag.write(C:\Users\User\Desktop\b_latour_iconoclash_images)

I did this and it worked the first time. But when I tried it with different paths it didn't work... not sure what I'm doing wrong.

**Comment by jscancella** [comment]
Hi @ahva-ubc , thanks for using Bagging! This is not a command line utility so unfortunately what you are trying to do won't work. 

 It is beyond the scope of this to teach you how to use this library, but if I may suggest some starting material that might help: 
- how to build this library: https://docs.gradle.org/current/userguide/userguide.html
- how to create a java project: https://www.jetbrains.com/help/idea/creating-and-running-your-first-java-application.html

If you have future problems please come back and open a new issue and we can work them out!
