### ISSUE TITLE
Convert domain objects to be completely immutable

### ISSUE THREAD

**Issue by jscancella** [jscancella/bagging#6]
Currently the domain objects allow for some changes after creation. Create a pull request for review that changes the domain objects (like Bag) to be completely immutable and throw modification error when trying to modify them.

**Comment by bhimak** [comment]
@jscancella I would like to use Builder pattern for all the domain objects to make them immutable. Any feedback for this design?

**Comment by jscancella** [comment]
Thanks for wanting to work on this! That sounds like it might work. Try modifing the code and submitting a pull request with what you think is a good design and we can discuss it more.

**Comment by jscancella** [comment]
For the maps in Bag() you will have to do something like 
```
Map<String, String> immutableMap = 
    Collections.unmodifiableMap(new LinkedHashMap<String, String>(realMap)); 
```
from https://stackoverflow.com/a/22636750

Also take a look at Builder Pattern in `Effective Java` by Joshua Bloch (pages 10-16) and minimize mutability (pages 80-86)

**Comment by jscancella** [comment]
Relates to #3

**Comment by bhimak** [comment]
@jscancella  I am running into a problem while making the Bag class immutable. com.github.jscancella.writer.BagWriter.write(Bag, Path) API is trying to set tag manifest explicitly. I would like to know your thoughts on my options here:

1. Create a new bag object using the bag object passed in and set the tag manifest. This would mean the passed object reference will not have the updated tag manifest value.
2. Create a setter API for this edge case? 

Same problem for this com.github.jscancella.writer.internal.BagCreator.createMetadataFile(Bag, Metadata) API also.

**Comment by jscancella** [comment]
My perference would be to return a new object and document it in the API call to make it clear that it is returning a new object.

The BagCreator will probably have to be overhauled since obviously directly setting it won't be an option anymore. Depending on if you implemented the builder pattern in the Bag class, you could use that to store the state between calls in BagCreator, or just get rid of BagCreator alltogether since the builder pattern would make it obsolete. I would imagine the API call to be something like this
```
Bag bag = Bag.builder().addDir(SOME_DIR).build();
bag = BagWriter.write(bag, SOME_OTHER_DIR);
```

**Comment by bhimak** [comment]
@jscancella Looks like the CricleCI build failed a couple of weeks ago. I couldn't find a way to re-build the project. I am ready to create PR for this enhancement. Can you rebuild the project to make sure everything is passing before my PR?

**Comment by jscancella** [comment]
that was just due to it unable to connect to the OWASP database. Go ahead and submit your pull request
