### ISSUE TITLE
Include classpath exception in bagging AGPL license

### ISSUE THREAD

**Issue by sprater** [jscancella/bagging#61]
We would like to use the bagging utility as a library dependency in some java software we are writing for digital preservation.  We are an academic institution;  we plan on releasing our developed software under the terms of a different license.

Please consider adding a GPL linking exception to your license to enable others to embed your package as a library dependency, then distribute their software under their own license terms.  This exception is very common in licenses covering libraries.

See https://en.wikipedia.org/wiki/GPL_linking_exception, in particular, the GNU Classpath exception.
Here's some example text that could be included in the license: https://enterprise.dejacode.com/licenses/public/linking-exception-agpl-3.0/#license-text

**Comment by jscancella** [comment]
> we plan on releasing our developed software under the terms of a different license

What license are you planning on releasing it under?

**Comment by sprater** [comment]
We plan on using the 2.0 Apache License.  https://opensource.org/licenses/Apache-2.0

**Comment by sprater** [comment]
We are hoping to release our preservation software in the first half of 2023. If you are open to changing or modifying the license, would it help if I were to submit a PR with a proposed change, that could then be merged in before we release our software?

**Comment by jscancella** [comment]
@sprater I would need to know more before allowing the linking exception. What is this software of yours that you are planning on releasing? I did add in the LICENSE that other licenses are available upon request if we need to go that route.

**Comment by sprater** [comment]
The software is a preservation system, consisting of a Java server and multiple workers, that unpack AIPs submitted to the system in bags, validate the contents, then store contents in a multiple backend remote storage systems (AWS, etc.).  The software is being developed at the University of Wisconsin - Madison, under the auspices of a Mellon grant.  One of the grant requirements is to make the software we develop freely available as open source for others to use.

**Comment by jscancella** [comment]
Maybe we can talk over the phone about this as I don't think a github issue is the best form. I tried looking on your profile for a email address to send you my phone number but couldn't find it. My email address is john.scancella@gmail.com

**Comment by sprater** [comment]
I just sent you my contact details from my work email account.

**Comment by sprater** [comment]
We have taken a different approach.  Thanks for your help, John.  This issue can be closed.
