### ISSUE TITLE
Consider using LGPL instead of AGPL

### ISSUE THREAD

**Issue by dmoles** [jscancella/bagging#72]
Effectively, AGPL limits the use of the library to other GPL/AGPL projects, which most existing Java digipres projects aren't.

**Comment by jscancella** [comment]
I am happy to talk with projects that want to use this library under a different license - they can contact me directly and we can come to a mutual agreement. However I am not changing the license of this library.

**Comment by dmoles** [comment]
OK. I think you're unlikely to get much uptake, at least from people that pay attention to licenses and are complying with yours (as opposed to people just blindly pulling from MavenCentral), but you do you.
